version: '3.3'
services:
  bayesapp:
    image: redam94/plutotest:latest
    ports:
     - 30015:8080
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
     - traefik-public
    logging:
      driver: json-file
    deploy:
      replicas: 4
      labels:
        traefik.http.services.juliaapp-secured.loadbalancer.sticky.cookie: 'true'
        traefik.http.routers.juliaapp.entrypoints: http
        traefik.http.services.juliaapp-secured.loadbalancer.server.port: '8080'
        traefik.http.middlewares.juliaapp.redirectscheme.scheme: https
        traefik.http.middlewares.juliaapp.redirectscheme.permanent: 'true'
        traefik.http.routers.juliaapp.rule: Host(`sliders.mattreda.pro`)
        traefik.constraint-label: traefik-public
        traefik.http.routers.juliaapp-secured.tls.certresolver: le
        traefik.docker.network: traefik-public
        traefik.enable: 'true'
        traefik.http.routers.juliaapp-secured.entrypoints: https
        traefik.http.routers.juliaapp-secured.rule: Host(`sliders.mattreda.pro`)
      restart_policy:
        condition: on-failure
networks:
  traefik-public:
    external: true